// List of Odisha districts for dropdown
export const ODISHA_DISTRICTS = [
  { en: 'Angul', or: 'ଅନୁଗୁଳ' },
  { en: 'Balangir', or: 'ବଲାଙ୍ଗିର' },
  { en: 'Balasore', or: 'ବାଲେଶ୍ୱର' },
  { en: 'Bargarh', or: 'ବରଗଡ଼' },
  { en: 'Bhadrak', or: 'ଭଦ୍ରକ' },
  { en: 'Boudh', or: 'ବୌଢ଼' },
  { en: 'Cuttack', or: 'କଟକ' },
  { en: 'Deogarh', or: 'ଦେବଗଡ଼' },
  { en: 'Dhenkanal', or: 'ଢେଙ୍କାନାଳ' },
  { en: 'Gajapati', or: 'ଗଜପତି' },
  { en: 'Ganjam', or: 'ଗଞ୍ଜାମ' },
  { en: 'Jagatsinghpur', or: 'ଜଗତସିଂହପୁର' },
  { en: 'Jajpur', or: 'ଯାଜପୁର' },
  { en: 'Jharsuguda', or: 'ଝାରସୁଗୁଡ଼ା' },
  { en: 'Kalahandi', or: 'କଳାହାଣ୍ଡି' },
  { en: 'Kandhamal', or: 'କନ୍ଧମାଳ' },
  { en: 'Kendrapara', or: 'କେନ୍ଦ୍ରାପଡ଼ା' },
  { en: 'Kendujhar', or: 'କେନ୍ଦୁଝର' },
  { en: 'Khordha', or: 'ଖୋର୍ଦ୍ଧା' },
  { en: 'Koraput', or: 'କୋରାପୁଟ' },
  { en: 'Malkangiri', or: 'ମାଲକାନଗିରି' },
  { en: 'Mayurbhanj', or: 'ମୟୂରଭଞ୍ଜ' },
  { en: 'Nabarangpur', or: 'ନବରଙ୍ଗପୁର' },
  { en: 'Nayagarh', or: 'ନୟାଗଡ଼' },
  { en: 'Nuapada', or: 'ନୂଆପଡ଼ା' },
  { en: 'Puri', or: 'ପୁରୀ' },
  { en: 'Rayagada', or: 'ରାୟଗଡ଼ା' },
  { en: 'Sambalpur', or: 'ସମ୍ବଲପୁର' },
  { en: 'Sonepur', or: 'ସୋନପୁର' },
  { en: 'Sundargarh', or: 'ସୁନ୍ଦରଗଡ଼' }
];
