import { jsPDF } from 'jspdf';
import { DailyMcq } from '../types';

/**
 * Generates a professional PDF exam paper for a Daily MCQ set.
 */
export async function exportDailyMcqToPdf(mcq: DailyMcq) {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // 1. Header
  doc.setFontSize(22);
  doc.setTextColor(0, 102, 204); // Premium Blue
  doc.text("UTKAL SKILL CENTRE", pageWidth / 2, y, { align: 'center' });
  
  y += 10;
  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text("EXAMINATION DEPARTMENT", pageWidth / 2, y, { align: 'center' });

  y += 15;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);

  // 2. Exam Info
  y += 10;
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.text(`SUBJECT: ${mcq.subject?.toUpperCase() || 'GENERAL'}`, margin, y);
  doc.text(`DATE: ${mcq.activeDate}`, pageWidth - margin, y, { align: 'right' });
  
  y += 7;
  doc.text(`CLASS: ${mcq.class.toUpperCase()}`, margin, y);
  doc.text(`MARKS: 50`, pageWidth - margin, y, { align: 'right' });

  y += 10;
  doc.line(margin, y, pageWidth - margin, y);

  // 3. Questions
  y += 15;
  if (!mcq.questions) return;

  mcq.questions.forEach((q, index) => {
    // Check for page break
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setFont('helvetica', 'bold');
    const qText = `${index + 1}. ${q.question} (${q.marks || 1} Mark)`;
    const splitQ = doc.splitTextToSize(qText, pageWidth - (margin * 2));
    doc.text(splitQ, margin, y);
    y += (splitQ.length * 7);

    if (q.type === 'mcq' && q.options) {
      doc.setFont('helvetica', 'normal');
      q.options.forEach((opt, optIdx) => {
        const prefix = String.fromCharCode(65 + optIdx) + ")";
        doc.text(`${prefix} ${opt}`, margin + 10, y);
        y += 7;
      });
    } else {
      // Space for subjective answer
      y += 15; 
      doc.setDrawColor(240);
      doc.line(margin + 10, y, pageWidth - margin, y);
      y += 10;
    }

    y += 5; // Gap between questions
  });

  // 4. Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by Utkal Skill Centre AI Engine", pageWidth / 2, 285, { align: 'center' });

  // Save the PDF
  doc.save(`USC_Exam_${mcq.class}_${mcq.subject}_${mcq.activeDate}.pdf`);
}
