export const subjectTranslations: Record<string, string> = {
  'Mathematics': 'ଗଣିତ',
  'Math': 'ଗଣିତ',
  'Science': 'ବିଜ୍ଞାନ',
  'English': 'ଇଂରାଜୀ',
  'Odia': 'ଓଡ଼ିଆ',
  'History': 'ଇତିହାସ',
  'Geography': 'ଭୂଗୋଳ',
  'Social Studies': 'ସାମାଜିକ ବିଜ୍ଞାନ',
  'Social Science': 'ସାମାଜିକ ବିଜ୍ଞାନ',
  'EVS': 'ପରିବେଶ ବିଜ୍ଞାନ',
  'General Knowledge': 'ସାଧାରଣ ଜ୍ଞାନ',
  'GK': 'ସାଧାରଣ ଜ୍ଞାନ',
  'Hindi': 'ହିନ୍ଦୀ',
  'Sanskrit': 'ସଂସ୍କୃତ',
  'Physics': 'ପଦାର୍ଥ ବିଜ୍ଞାନ',
  'Chemistry': 'ରସାୟନ ବିଜ୍ଞାନ',
  'Biology': 'ଜୀବ ବିଜ୍ଞାନ',
  'Art & Health Education': 'କଳା ଏବଂ ସ୍ୱାସ୍ଥ୍ୟ ଶିକ୍ଷା',
  'Art Education': 'କଳା ଶିକ୍ଷା',
  'Physical Education & Well-being': 'ଶାରୀରିକ ଶିକ୍ଷା ଏବଂ ସୁସ୍ଥତା',
  'Vocational Education': 'ଧନ୍ଦାମୂଳକ ଶିକ୍ଷା',
  'Environmental & Population Education': 'ପରିବେଶ ଏବଂ ଜନସଂଖ୍ୟା ଶିକ୍ଷା',
  'Aspirational Components': 'ଆକାଂକ୍ଷାମୂଳକ ଉପାଦାନ',
  'Science (Jigyansa)': 'ବିଜ୍ଞାନ (ଜିଜ୍ଞାସା)'
};
